/*
 * generated by Xtext 2.28.0
 */
package cafev.vform;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VFormDslStandaloneSetup extends VFormDslStandaloneSetupGenerated {

	public static void doSetup() {
		new VFormDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
