/*
 * generated by Xtext 2.28.0
 */
package cafev.vform.parser.antlr;

import cafev.vform.parser.antlr.internal.InternalVFormDslParser;
import cafev.vform.services.VFormDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class VFormDslParser extends AbstractAntlrParser {

	@Inject
	private VFormDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVFormDslParser createParser(XtextTokenStream stream) {
		return new InternalVFormDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public VFormDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VFormDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
