/**
 * generated by Xtext 2.28.0
 */
package cafev.vform.vFormDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see cafev.vform.vFormDsl.VFormDslFactory
 * @model kind="package"
 * @generated
 */
public interface VFormDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "vFormDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.vform.cafev/VFormDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "vFormDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VFormDslPackage eINSTANCE = cafev.vform.vFormDsl.impl.VFormDslPackageImpl.init();

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.ModelImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Form Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FORM_LAYOUT = 0;

  /**
   * The feature id for the '<em><b>Form Input</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FORM_INPUT = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.FormLayoutImpl <em>Form Layout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.FormLayoutImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormLayout()
   * @generated
   */
  int FORM_LAYOUT = 1;

  /**
   * The feature id for the '<em><b>Layout</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_LAYOUT__LAYOUT = 0;

  /**
   * The number of structural features of the '<em>Form Layout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_LAYOUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.FormInputImpl <em>Form Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.FormInputImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInput()
   * @generated
   */
  int FORM_INPUT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT__NAME = 0;

  /**
   * The number of structural features of the '<em>Form Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.FormInputBasicImpl <em>Form Input Basic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.FormInputBasicImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputBasic()
   * @generated
   */
  int FORM_INPUT_BASIC = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_BASIC__NAME = FORM_INPUT__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_BASIC__TYPE = FORM_INPUT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Form Input Basic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_BASIC_FEATURE_COUNT = FORM_INPUT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.FormInputRangeImpl <em>Form Input Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.FormInputRangeImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputRange()
   * @generated
   */
  int FORM_INPUT_RANGE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_RANGE__NAME = FORM_INPUT__NAME;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_RANGE__MIN = FORM_INPUT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_RANGE__MAX = FORM_INPUT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Form Input Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_RANGE_FEATURE_COUNT = FORM_INPUT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.FormInputSelectImpl <em>Form Input Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.FormInputSelectImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputSelect()
   * @generated
   */
  int FORM_INPUT_SELECT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_SELECT__NAME = FORM_INPUT__NAME;

  /**
   * The feature id for the '<em><b>Option</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_SELECT__OPTION = FORM_INPUT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Form Input Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_SELECT_FEATURE_COUNT = FORM_INPUT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.OptionImpl <em>Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.OptionImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getOption()
   * @generated
   */
  int OPTION = 6;

  /**
   * The number of structural features of the '<em>Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.DataOptionImpl <em>Data Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.DataOptionImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getDataOption()
   * @generated
   */
  int DATA_OPTION = 7;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_OPTION__DATA = OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Data Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_OPTION_FEATURE_COUNT = OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.EnumOptionImpl <em>Enum Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.EnumOptionImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getEnumOption()
   * @generated
   */
  int ENUM_OPTION = 8;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_OPTION__DATA = OPTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Enum Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_OPTION_FEATURE_COUNT = OPTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.NumberOptionImpl <em>Number Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.NumberOptionImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getNumberOption()
   * @generated
   */
  int NUMBER_OPTION = 9;

  /**
   * The feature id for the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_OPTION__MIN = OPTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_OPTION__MAX = OPTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_OPTION__RANGE = OPTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Number Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_OPTION_FEATURE_COUNT = OPTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.FormInputSearchImpl <em>Form Input Search</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.FormInputSearchImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputSearch()
   * @generated
   */
  int FORM_INPUT_SEARCH = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_SEARCH__NAME = FORM_INPUT__NAME;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_SEARCH__DATA = FORM_INPUT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Form Input Search</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_SEARCH_FEATURE_COUNT = FORM_INPUT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.OptionItemImpl <em>Option Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.OptionItemImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getOptionItem()
   * @generated
   */
  int OPTION_ITEM = 11;

  /**
   * The number of structural features of the '<em>Option Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTION_ITEM_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.StringOptionItemImpl <em>String Option Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.StringOptionItemImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getStringOptionItem()
   * @generated
   */
  int STRING_OPTION_ITEM = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_OPTION_ITEM__VALUE = OPTION_ITEM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Option Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_OPTION_ITEM_FEATURE_COUNT = OPTION_ITEM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.IntOptionItemImpl <em>Int Option Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.IntOptionItemImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getIntOptionItem()
   * @generated
   */
  int INT_OPTION_ITEM = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_OPTION_ITEM__VALUE = OPTION_ITEM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Option Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_OPTION_ITEM_FEATURE_COUNT = OPTION_ITEM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.DataOptionItemImpl <em>Data Option Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.DataOptionItemImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getDataOptionItem()
   * @generated
   */
  int DATA_OPTION_ITEM = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_OPTION_ITEM__VALUE = OPTION_ITEM_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Data Option Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_OPTION_ITEM_FEATURE_COUNT = OPTION_ITEM_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.FormInputGroupImpl <em>Form Input Group</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.FormInputGroupImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputGroup()
   * @generated
   */
  int FORM_INPUT_GROUP = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_GROUP__NAME = FORM_INPUT__NAME;

  /**
   * The feature id for the '<em><b>Group Inputs</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_GROUP__GROUP_INPUTS = FORM_INPUT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Form Input Group</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_INPUT_GROUP_FEATURE_COUNT = FORM_INPUT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.DataImpl <em>Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.DataImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getData()
   * @generated
   */
  int DATA = 16;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA__LABEL = 0;

  /**
   * The number of structural features of the '<em>Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.StringDataImpl <em>String Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.StringDataImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getStringData()
   * @generated
   */
  int STRING_DATA = 17;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DATA__LABEL = DATA__LABEL;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DATA__VALUE = DATA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_DATA_FEATURE_COUNT = DATA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.impl.IntDataImpl <em>Int Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.impl.IntDataImpl
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getIntData()
   * @generated
   */
  int INT_DATA = 18;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_DATA__LABEL = DATA__LABEL;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_DATA__VALUE = DATA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_DATA_FEATURE_COUNT = DATA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.BasicInputType <em>Basic Input Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.BasicInputType
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getBasicInputType()
   * @generated
   */
  int BASIC_INPUT_TYPE = 19;

  /**
   * The meta object id for the '{@link cafev.vform.vFormDsl.Layout <em>Layout</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cafev.vform.vFormDsl.Layout
   * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getLayout()
   * @generated
   */
  int LAYOUT = 20;


  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see cafev.vform.vFormDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link cafev.vform.vFormDsl.Model#getFormLayout <em>Form Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Form Layout</em>'.
   * @see cafev.vform.vFormDsl.Model#getFormLayout()
   * @see #getModel()
   * @generated
   */
  EReference getModel_FormLayout();

  /**
   * Returns the meta object for the containment reference list '{@link cafev.vform.vFormDsl.Model#getFormInput <em>Form Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Form Input</em>'.
   * @see cafev.vform.vFormDsl.Model#getFormInput()
   * @see #getModel()
   * @generated
   */
  EReference getModel_FormInput();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.FormLayout <em>Form Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form Layout</em>'.
   * @see cafev.vform.vFormDsl.FormLayout
   * @generated
   */
  EClass getFormLayout();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.FormLayout#getLayout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Layout</em>'.
   * @see cafev.vform.vFormDsl.FormLayout#getLayout()
   * @see #getFormLayout()
   * @generated
   */
  EAttribute getFormLayout_Layout();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.FormInput <em>Form Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form Input</em>'.
   * @see cafev.vform.vFormDsl.FormInput
   * @generated
   */
  EClass getFormInput();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.FormInput#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cafev.vform.vFormDsl.FormInput#getName()
   * @see #getFormInput()
   * @generated
   */
  EAttribute getFormInput_Name();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.FormInputBasic <em>Form Input Basic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form Input Basic</em>'.
   * @see cafev.vform.vFormDsl.FormInputBasic
   * @generated
   */
  EClass getFormInputBasic();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.FormInputBasic#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see cafev.vform.vFormDsl.FormInputBasic#getType()
   * @see #getFormInputBasic()
   * @generated
   */
  EAttribute getFormInputBasic_Type();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.FormInputRange <em>Form Input Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form Input Range</em>'.
   * @see cafev.vform.vFormDsl.FormInputRange
   * @generated
   */
  EClass getFormInputRange();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.FormInputRange#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see cafev.vform.vFormDsl.FormInputRange#getMin()
   * @see #getFormInputRange()
   * @generated
   */
  EAttribute getFormInputRange_Min();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.FormInputRange#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see cafev.vform.vFormDsl.FormInputRange#getMax()
   * @see #getFormInputRange()
   * @generated
   */
  EAttribute getFormInputRange_Max();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.FormInputSelect <em>Form Input Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form Input Select</em>'.
   * @see cafev.vform.vFormDsl.FormInputSelect
   * @generated
   */
  EClass getFormInputSelect();

  /**
   * Returns the meta object for the containment reference '{@link cafev.vform.vFormDsl.FormInputSelect#getOption <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Option</em>'.
   * @see cafev.vform.vFormDsl.FormInputSelect#getOption()
   * @see #getFormInputSelect()
   * @generated
   */
  EReference getFormInputSelect_Option();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.Option <em>Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option</em>'.
   * @see cafev.vform.vFormDsl.Option
   * @generated
   */
  EClass getOption();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.DataOption <em>Data Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Option</em>'.
   * @see cafev.vform.vFormDsl.DataOption
   * @generated
   */
  EClass getDataOption();

  /**
   * Returns the meta object for the containment reference list '{@link cafev.vform.vFormDsl.DataOption#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see cafev.vform.vFormDsl.DataOption#getData()
   * @see #getDataOption()
   * @generated
   */
  EReference getDataOption_Data();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.EnumOption <em>Enum Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Option</em>'.
   * @see cafev.vform.vFormDsl.EnumOption
   * @generated
   */
  EClass getEnumOption();

  /**
   * Returns the meta object for the containment reference list '{@link cafev.vform.vFormDsl.EnumOption#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see cafev.vform.vFormDsl.EnumOption#getData()
   * @see #getEnumOption()
   * @generated
   */
  EReference getEnumOption_Data();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.NumberOption <em>Number Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Option</em>'.
   * @see cafev.vform.vFormDsl.NumberOption
   * @generated
   */
  EClass getNumberOption();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.NumberOption#getMin <em>Min</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min</em>'.
   * @see cafev.vform.vFormDsl.NumberOption#getMin()
   * @see #getNumberOption()
   * @generated
   */
  EAttribute getNumberOption_Min();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.NumberOption#getMax <em>Max</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max</em>'.
   * @see cafev.vform.vFormDsl.NumberOption#getMax()
   * @see #getNumberOption()
   * @generated
   */
  EAttribute getNumberOption_Max();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.NumberOption#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Range</em>'.
   * @see cafev.vform.vFormDsl.NumberOption#getRange()
   * @see #getNumberOption()
   * @generated
   */
  EAttribute getNumberOption_Range();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.FormInputSearch <em>Form Input Search</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form Input Search</em>'.
   * @see cafev.vform.vFormDsl.FormInputSearch
   * @generated
   */
  EClass getFormInputSearch();

  /**
   * Returns the meta object for the containment reference list '{@link cafev.vform.vFormDsl.FormInputSearch#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see cafev.vform.vFormDsl.FormInputSearch#getData()
   * @see #getFormInputSearch()
   * @generated
   */
  EReference getFormInputSearch_Data();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.OptionItem <em>Option Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Option Item</em>'.
   * @see cafev.vform.vFormDsl.OptionItem
   * @generated
   */
  EClass getOptionItem();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.StringOptionItem <em>String Option Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Option Item</em>'.
   * @see cafev.vform.vFormDsl.StringOptionItem
   * @generated
   */
  EClass getStringOptionItem();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.StringOptionItem#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see cafev.vform.vFormDsl.StringOptionItem#getValue()
   * @see #getStringOptionItem()
   * @generated
   */
  EAttribute getStringOptionItem_Value();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.IntOptionItem <em>Int Option Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Option Item</em>'.
   * @see cafev.vform.vFormDsl.IntOptionItem
   * @generated
   */
  EClass getIntOptionItem();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.IntOptionItem#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see cafev.vform.vFormDsl.IntOptionItem#getValue()
   * @see #getIntOptionItem()
   * @generated
   */
  EAttribute getIntOptionItem_Value();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.DataOptionItem <em>Data Option Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Option Item</em>'.
   * @see cafev.vform.vFormDsl.DataOptionItem
   * @generated
   */
  EClass getDataOptionItem();

  /**
   * Returns the meta object for the containment reference '{@link cafev.vform.vFormDsl.DataOptionItem#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see cafev.vform.vFormDsl.DataOptionItem#getValue()
   * @see #getDataOptionItem()
   * @generated
   */
  EReference getDataOptionItem_Value();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.FormInputGroup <em>Form Input Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form Input Group</em>'.
   * @see cafev.vform.vFormDsl.FormInputGroup
   * @generated
   */
  EClass getFormInputGroup();

  /**
   * Returns the meta object for the reference '{@link cafev.vform.vFormDsl.FormInputGroup#getGroupInputs <em>Group Inputs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Group Inputs</em>'.
   * @see cafev.vform.vFormDsl.FormInputGroup#getGroupInputs()
   * @see #getFormInputGroup()
   * @generated
   */
  EReference getFormInputGroup_GroupInputs();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.Data <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data</em>'.
   * @see cafev.vform.vFormDsl.Data
   * @generated
   */
  EClass getData();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.Data#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see cafev.vform.vFormDsl.Data#getLabel()
   * @see #getData()
   * @generated
   */
  EAttribute getData_Label();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.StringData <em>String Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Data</em>'.
   * @see cafev.vform.vFormDsl.StringData
   * @generated
   */
  EClass getStringData();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.StringData#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see cafev.vform.vFormDsl.StringData#getValue()
   * @see #getStringData()
   * @generated
   */
  EAttribute getStringData_Value();

  /**
   * Returns the meta object for class '{@link cafev.vform.vFormDsl.IntData <em>Int Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Data</em>'.
   * @see cafev.vform.vFormDsl.IntData
   * @generated
   */
  EClass getIntData();

  /**
   * Returns the meta object for the attribute '{@link cafev.vform.vFormDsl.IntData#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see cafev.vform.vFormDsl.IntData#getValue()
   * @see #getIntData()
   * @generated
   */
  EAttribute getIntData_Value();

  /**
   * Returns the meta object for enum '{@link cafev.vform.vFormDsl.BasicInputType <em>Basic Input Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Basic Input Type</em>'.
   * @see cafev.vform.vFormDsl.BasicInputType
   * @generated
   */
  EEnum getBasicInputType();

  /**
   * Returns the meta object for enum '{@link cafev.vform.vFormDsl.Layout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Layout</em>'.
   * @see cafev.vform.vFormDsl.Layout
   * @generated
   */
  EEnum getLayout();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VFormDslFactory getVFormDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.ModelImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Form Layout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FORM_LAYOUT = eINSTANCE.getModel_FormLayout();

    /**
     * The meta object literal for the '<em><b>Form Input</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FORM_INPUT = eINSTANCE.getModel_FormInput();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.FormLayoutImpl <em>Form Layout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.FormLayoutImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormLayout()
     * @generated
     */
    EClass FORM_LAYOUT = eINSTANCE.getFormLayout();

    /**
     * The meta object literal for the '<em><b>Layout</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORM_LAYOUT__LAYOUT = eINSTANCE.getFormLayout_Layout();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.FormInputImpl <em>Form Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.FormInputImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInput()
     * @generated
     */
    EClass FORM_INPUT = eINSTANCE.getFormInput();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORM_INPUT__NAME = eINSTANCE.getFormInput_Name();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.FormInputBasicImpl <em>Form Input Basic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.FormInputBasicImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputBasic()
     * @generated
     */
    EClass FORM_INPUT_BASIC = eINSTANCE.getFormInputBasic();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORM_INPUT_BASIC__TYPE = eINSTANCE.getFormInputBasic_Type();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.FormInputRangeImpl <em>Form Input Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.FormInputRangeImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputRange()
     * @generated
     */
    EClass FORM_INPUT_RANGE = eINSTANCE.getFormInputRange();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORM_INPUT_RANGE__MIN = eINSTANCE.getFormInputRange_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORM_INPUT_RANGE__MAX = eINSTANCE.getFormInputRange_Max();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.FormInputSelectImpl <em>Form Input Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.FormInputSelectImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputSelect()
     * @generated
     */
    EClass FORM_INPUT_SELECT = eINSTANCE.getFormInputSelect();

    /**
     * The meta object literal for the '<em><b>Option</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORM_INPUT_SELECT__OPTION = eINSTANCE.getFormInputSelect_Option();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.OptionImpl <em>Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.OptionImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getOption()
     * @generated
     */
    EClass OPTION = eINSTANCE.getOption();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.DataOptionImpl <em>Data Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.DataOptionImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getDataOption()
     * @generated
     */
    EClass DATA_OPTION = eINSTANCE.getDataOption();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_OPTION__DATA = eINSTANCE.getDataOption_Data();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.EnumOptionImpl <em>Enum Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.EnumOptionImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getEnumOption()
     * @generated
     */
    EClass ENUM_OPTION = eINSTANCE.getEnumOption();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENUM_OPTION__DATA = eINSTANCE.getEnumOption_Data();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.NumberOptionImpl <em>Number Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.NumberOptionImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getNumberOption()
     * @generated
     */
    EClass NUMBER_OPTION = eINSTANCE.getNumberOption();

    /**
     * The meta object literal for the '<em><b>Min</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_OPTION__MIN = eINSTANCE.getNumberOption_Min();

    /**
     * The meta object literal for the '<em><b>Max</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_OPTION__MAX = eINSTANCE.getNumberOption_Max();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_OPTION__RANGE = eINSTANCE.getNumberOption_Range();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.FormInputSearchImpl <em>Form Input Search</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.FormInputSearchImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputSearch()
     * @generated
     */
    EClass FORM_INPUT_SEARCH = eINSTANCE.getFormInputSearch();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORM_INPUT_SEARCH__DATA = eINSTANCE.getFormInputSearch_Data();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.OptionItemImpl <em>Option Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.OptionItemImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getOptionItem()
     * @generated
     */
    EClass OPTION_ITEM = eINSTANCE.getOptionItem();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.StringOptionItemImpl <em>String Option Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.StringOptionItemImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getStringOptionItem()
     * @generated
     */
    EClass STRING_OPTION_ITEM = eINSTANCE.getStringOptionItem();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_OPTION_ITEM__VALUE = eINSTANCE.getStringOptionItem_Value();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.IntOptionItemImpl <em>Int Option Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.IntOptionItemImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getIntOptionItem()
     * @generated
     */
    EClass INT_OPTION_ITEM = eINSTANCE.getIntOptionItem();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_OPTION_ITEM__VALUE = eINSTANCE.getIntOptionItem_Value();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.DataOptionItemImpl <em>Data Option Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.DataOptionItemImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getDataOptionItem()
     * @generated
     */
    EClass DATA_OPTION_ITEM = eINSTANCE.getDataOptionItem();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATA_OPTION_ITEM__VALUE = eINSTANCE.getDataOptionItem_Value();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.FormInputGroupImpl <em>Form Input Group</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.FormInputGroupImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getFormInputGroup()
     * @generated
     */
    EClass FORM_INPUT_GROUP = eINSTANCE.getFormInputGroup();

    /**
     * The meta object literal for the '<em><b>Group Inputs</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORM_INPUT_GROUP__GROUP_INPUTS = eINSTANCE.getFormInputGroup_GroupInputs();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.DataImpl <em>Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.DataImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getData()
     * @generated
     */
    EClass DATA = eINSTANCE.getData();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATA__LABEL = eINSTANCE.getData_Label();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.StringDataImpl <em>String Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.StringDataImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getStringData()
     * @generated
     */
    EClass STRING_DATA = eINSTANCE.getStringData();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_DATA__VALUE = eINSTANCE.getStringData_Value();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.impl.IntDataImpl <em>Int Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.impl.IntDataImpl
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getIntData()
     * @generated
     */
    EClass INT_DATA = eINSTANCE.getIntData();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_DATA__VALUE = eINSTANCE.getIntData_Value();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.BasicInputType <em>Basic Input Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.BasicInputType
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getBasicInputType()
     * @generated
     */
    EEnum BASIC_INPUT_TYPE = eINSTANCE.getBasicInputType();

    /**
     * The meta object literal for the '{@link cafev.vform.vFormDsl.Layout <em>Layout</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cafev.vform.vFormDsl.Layout
     * @see cafev.vform.vFormDsl.impl.VFormDslPackageImpl#getLayout()
     * @generated
     */
    EEnum LAYOUT = eINSTANCE.getLayout();

  }

} //VFormDslPackage
