/**
 * generated by Xtext 2.25.0
 */
package cafeV.dsl.vforms.vformDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cafeV.dsl.vforms.vformDSL.Model#getFormLayout <em>Form Layout</em>}</li>
 *   <li>{@link cafeV.dsl.vforms.vformDSL.Model#getFormInput <em>Form Input</em>}</li>
 * </ul>
 *
 * @see cafeV.dsl.vforms.vformDSL.VformDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Form Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Form Layout</em>' containment reference.
   * @see #setFormLayout(FormLayout)
   * @see cafeV.dsl.vforms.vformDSL.VformDSLPackage#getModel_FormLayout()
   * @model containment="true"
   * @generated
   */
  FormLayout getFormLayout();

  /**
   * Sets the value of the '{@link cafeV.dsl.vforms.vformDSL.Model#getFormLayout <em>Form Layout</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Form Layout</em>' containment reference.
   * @see #getFormLayout()
   * @generated
   */
  void setFormLayout(FormLayout value);

  /**
   * Returns the value of the '<em><b>Form Input</b></em>' containment reference list.
   * The list contents are of type {@link cafeV.dsl.vforms.vformDSL.FormInput}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Form Input</em>' containment reference list.
   * @see cafeV.dsl.vforms.vformDSL.VformDSLPackage#getModel_FormInput()
   * @model containment="true"
   * @generated
   */
  EList<FormInput> getFormInput();

} // Model
