/**
 * generated by Xtext 2.25.0
 */
package cafeV.dsl.vforms.vformDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cafeV.dsl.vforms.vformDSL.Range#getInputName <em>Input Name</em>}</li>
 *   <li>{@link cafeV.dsl.vforms.vformDSL.Range#getMin <em>Min</em>}</li>
 *   <li>{@link cafeV.dsl.vforms.vformDSL.Range#getMax <em>Max</em>}</li>
 * </ul>
 *
 * @see cafeV.dsl.vforms.vformDSL.VformDSLPackage#getRange()
 * @model
 * @generated
 */
public interface Range extends EObject
{
  /**
   * Returns the value of the '<em><b>Input Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Name</em>' attribute.
   * @see #setInputName(String)
   * @see cafeV.dsl.vforms.vformDSL.VformDSLPackage#getRange_InputName()
   * @model
   * @generated
   */
  String getInputName();

  /**
   * Sets the value of the '{@link cafeV.dsl.vforms.vformDSL.Range#getInputName <em>Input Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input Name</em>' attribute.
   * @see #getInputName()
   * @generated
   */
  void setInputName(String value);

  /**
   * Returns the value of the '<em><b>Min</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min</em>' attribute.
   * @see #setMin(int)
   * @see cafeV.dsl.vforms.vformDSL.VformDSLPackage#getRange_Min()
   * @model
   * @generated
   */
  int getMin();

  /**
   * Sets the value of the '{@link cafeV.dsl.vforms.vformDSL.Range#getMin <em>Min</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min</em>' attribute.
   * @see #getMin()
   * @generated
   */
  void setMin(int value);

  /**
   * Returns the value of the '<em><b>Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max</em>' attribute.
   * @see #setMax(int)
   * @see cafeV.dsl.vforms.vformDSL.VformDSLPackage#getRange_Max()
   * @model
   * @generated
   */
  int getMax();

  /**
   * Sets the value of the '{@link cafeV.dsl.vforms.vformDSL.Range#getMax <em>Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max</em>' attribute.
   * @see #getMax()
   * @generated
   */
  void setMax(int value);

} // Range
