<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="data_Description" nsURI="http://www.example.org/data_Description"
    nsPrefix="data_Description">
  <eClassifiers xsi:type="ecore:EClass" name="CategoricalStat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="frequencyTable" upperBound="-1"
        eType="#//freqTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericalStat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="std" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FreqencyTable" upperBound="-1"
        eType="#//freqTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="freqTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="numericalstat" upperBound="-1"
        eType="#//NumericalStat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categoricalstat" upperBound="-1"
        eType="#//CategoricalStat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
</ecore:EPackage>
