/*
 * generated by Xtext 2.30.0
 */
package cafev.vform.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link VFormDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractVFormDslWebModule extends DefaultWebModule {

}
