/**
 * generated by Xtext 2.25.0
 */
package cafeV.dsl.vforms.vformDSL.impl;

import cafeV.dsl.vforms.vformDSL.Checkbox;
import cafeV.dsl.vforms.vformDSL.VformDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Checkbox</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cafeV.dsl.vforms.vformDSL.impl.CheckboxImpl#getInputName <em>Input Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CheckboxImpl extends MinimalEObjectImpl.Container implements Checkbox
{
  /**
   * The default value of the '{@link #getInputName() <em>Input Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputName()
   * @generated
   * @ordered
   */
  protected static final String INPUT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInputName() <em>Input Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputName()
   * @generated
   * @ordered
   */
  protected String inputName = INPUT_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CheckboxImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VformDSLPackage.Literals.CHECKBOX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInputName()
  {
    return inputName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInputName(String newInputName)
  {
    String oldInputName = inputName;
    inputName = newInputName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VformDSLPackage.CHECKBOX__INPUT_NAME, oldInputName, inputName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VformDSLPackage.CHECKBOX__INPUT_NAME:
        return getInputName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VformDSLPackage.CHECKBOX__INPUT_NAME:
        setInputName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VformDSLPackage.CHECKBOX__INPUT_NAME:
        setInputName(INPUT_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VformDSLPackage.CHECKBOX__INPUT_NAME:
        return INPUT_NAME_EDEFAULT == null ? inputName != null : !INPUT_NAME_EDEFAULT.equals(inputName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (inputName: ");
    result.append(inputName);
    result.append(')');
    return result.toString();
  }

} //CheckboxImpl
