/*
 * generated by Xtext 2.30.0
 */
package yamtl.vforms;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class VFormsDslStandaloneSetup extends VFormsDslStandaloneSetupGenerated {

	public static void doSetup() {
		new VFormsDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
