/*
 * generated by Xtext 2.28.0
 */
package cafev.vform.ide;

import cafev.vform.VFormDslRuntimeModule;
import cafev.vform.VFormDslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VFormDslIdeSetup extends VFormDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VFormDslRuntimeModule(), new VFormDslIdeModule()));
	}
	
}
