/*
 * generated by Xtext 2.28.0
 */
package cafev.vform.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class VFormDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFormLayoutKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFormLayoutAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFormLayoutFormLayoutParserRuleCall_1_0 = (RuleCall)cFormLayoutAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cFormInputsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFormInputAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFormInputFormInputParserRuleCall_5_0 = (RuleCall)cFormInputAssignment_5.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Model:
		//    "formLayout:" formLayout=FormLayout ","
		//    "formInputs:" "["
		//        (formInput+=FormInput*)
		//    "]"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"formLayout:" formLayout=FormLayout ","
		//"formInputs:" "["
		//    (formInput+=FormInput*)
		//"]"
		public Group getGroup() { return cGroup; }
		
		//"formLayout:"
		public Keyword getFormLayoutKeyword_0() { return cFormLayoutKeyword_0; }
		
		//formLayout=FormLayout
		public Assignment getFormLayoutAssignment_1() { return cFormLayoutAssignment_1; }
		
		//FormLayout
		public RuleCall getFormLayoutFormLayoutParserRuleCall_1_0() { return cFormLayoutFormLayoutParserRuleCall_1_0; }
		
		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//"formInputs:"
		public Keyword getFormInputsKeyword_3() { return cFormInputsKeyword_3; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_4() { return cLeftSquareBracketKeyword_4; }
		
		//(formInput+=FormInput*)
		public Assignment getFormInputAssignment_5() { return cFormInputAssignment_5; }
		
		//FormInput
		public RuleCall getFormInputFormInputParserRuleCall_5_0() { return cFormInputFormInputParserRuleCall_5_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_6() { return cRightSquareBracketKeyword_6; }
	}
	public class FormLayoutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormLayout");
		private final Assignment cLayoutAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLayoutLayoutEnumRuleCall_0 = (RuleCall)cLayoutAssignment.eContents().get(0);
		
		//FormLayout:
		//    layout=Layout;
		@Override public ParserRule getRule() { return rule; }
		
		//layout=Layout
		public Assignment getLayoutAssignment() { return cLayoutAssignment; }
		
		//Layout
		public RuleCall getLayoutLayoutEnumRuleCall_0() { return cLayoutLayoutEnumRuleCall_0; }
	}
	public class FormInputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInput");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFormInputBasicParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFormInputRangeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFormInputSelectParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFormInputSearchParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cFormInputGroupParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//FormInput:
		//    FormInputBasic | FormInputRange | FormInputSelect| FormInputSearch | FormInputGroup
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//FormInputBasic | FormInputRange | FormInputSelect| FormInputSearch | FormInputGroup
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FormInputBasic
		public RuleCall getFormInputBasicParserRuleCall_0() { return cFormInputBasicParserRuleCall_0; }
		
		//FormInputRange
		public RuleCall getFormInputRangeParserRuleCall_1() { return cFormInputRangeParserRuleCall_1; }
		
		//FormInputSelect
		public RuleCall getFormInputSelectParserRuleCall_2() { return cFormInputSelectParserRuleCall_2; }
		
		//FormInputSearch
		public RuleCall getFormInputSearchParserRuleCall_3() { return cFormInputSearchParserRuleCall_3; }
		
		//FormInputGroup
		public RuleCall getFormInputGroupParserRuleCall_4() { return cFormInputGroupParserRuleCall_4; }
	}
	public class FormInputBasicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputBasic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTypeInputTypeEnumRuleCall_5_0 = (RuleCall)cTypeAssignment_5.eContents().get(0);
		
		//FormInputBasic:
		//    "name" ":" name=STRING
		//    "type" ":" type=InputType
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"name" ":" name=STRING
		//"type" ":" type=InputType
		public Group getGroup() { return cGroup; }
		
		//"name"
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//"type"
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//type=InputType
		public Assignment getTypeAssignment_5() { return cTypeAssignment_5; }
		
		//InputType
		public RuleCall getTypeInputTypeEnumRuleCall_5_0() { return cTypeInputTypeEnumRuleCall_5_0; }
	}
	public class FormInputRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRANGEKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cMinKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cMinAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cMinINTTerminalRuleCall_9_0 = (RuleCall)cMinAssignment_9.eContents().get(0);
		private final Keyword cCommaKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cMaxKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cMaxAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cMaxINTTerminalRuleCall_12_0 = (RuleCall)cMaxAssignment_12.eContents().get(0);
		
		//FormInputRange:
		//    "name" ":" name=STRING ","
		//    "type" ":" "RANGE" ","
		//    "min:" min=INT ","
		//    "max:" max=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"name" ":" name=STRING ","
		//"type" ":" "RANGE" ","
		//"min:" min=INT ","
		//"max:" max=INT
		public Group getGroup() { return cGroup; }
		
		//"name"
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"type"
		public Keyword getTypeKeyword_4() { return cTypeKeyword_4; }
		
		//":"
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//"RANGE"
		public Keyword getRANGEKeyword_6() { return cRANGEKeyword_6; }
		
		//","
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//"min:"
		public Keyword getMinKeyword_8() { return cMinKeyword_8; }
		
		//min=INT
		public Assignment getMinAssignment_9() { return cMinAssignment_9; }
		
		//INT
		public RuleCall getMinINTTerminalRuleCall_9_0() { return cMinINTTerminalRuleCall_9_0; }
		
		//","
		public Keyword getCommaKeyword_10() { return cCommaKeyword_10; }
		
		//"max:"
		public Keyword getMaxKeyword_11() { return cMaxKeyword_11; }
		
		//max=INT
		public Assignment getMaxAssignment_12() { return cMaxAssignment_12; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_12_0() { return cMaxINTTerminalRuleCall_12_0; }
	}
	public class FormInputSelectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputSelect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cSELECTKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cOptionsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cOptionAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cOptionOptionParserRuleCall_10_0 = (RuleCall)cOptionAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//FormInputSelect:
		//    "name" ":" name=STRING ","
		//    "type" ":" "SELECT" ","
		//    "options:" "{" option=Option "}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"name" ":" name=STRING ","
		//"type" ":" "SELECT" ","
		//"options:" "{" option=Option "}"
		public Group getGroup() { return cGroup; }
		
		//"name"
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"type"
		public Keyword getTypeKeyword_4() { return cTypeKeyword_4; }
		
		//":"
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//"SELECT"
		public Keyword getSELECTKeyword_6() { return cSELECTKeyword_6; }
		
		//","
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//"options:"
		public Keyword getOptionsKeyword_8() { return cOptionsKeyword_8; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//option=Option
		public Assignment getOptionAssignment_10() { return cOptionAssignment_10; }
		
		//Option
		public RuleCall getOptionOptionParserRuleCall_10_0() { return cOptionOptionParserRuleCall_10_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.Option");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDataOptionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEnumOptionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNumberOptionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Option:
		//    DataOption | EnumOption | NumberOption
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//DataOption | EnumOption | NumberOption
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DataOption
		public RuleCall getDataOptionParserRuleCall_0() { return cDataOptionParserRuleCall_0; }
		
		//EnumOption
		public RuleCall getEnumOptionParserRuleCall_1() { return cEnumOptionParserRuleCall_1; }
		
		//NumberOption
		public RuleCall getNumberOptionParserRuleCall_2() { return cNumberOptionParserRuleCall_2; }
	}
	public class DataOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.DataOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cDataKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDataKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDataAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDataDataParserRuleCall_5_0 = (RuleCall)cDataAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDataAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_6_1_0 = (RuleCall)cDataAssignment_6_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//DataOption:
		//    "optionType:" "data" ","
		//     "data:" "[" data+=Data ("," data+=Data)* "]"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"optionType:" "data" ","
		// "data:" "[" data+=Data ("," data+=Data)* "]"
		public Group getGroup() { return cGroup; }
		
		//"optionType:"
		public Keyword getOptionTypeKeyword_0() { return cOptionTypeKeyword_0; }
		
		//"data"
		public Keyword getDataKeyword_1() { return cDataKeyword_1; }
		
		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//"data:"
		public Keyword getDataKeyword_3() { return cDataKeyword_3; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_4() { return cLeftSquareBracketKeyword_4; }
		
		//data+=Data
		public Assignment getDataAssignment_5() { return cDataAssignment_5; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_5_0() { return cDataDataParserRuleCall_5_0; }
		
		//("," data+=Data)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//data+=Data
		public Assignment getDataAssignment_6_1() { return cDataAssignment_6_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_6_1_0() { return cDataDataParserRuleCall_6_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_7() { return cRightSquareBracketKeyword_7; }
	}
	public class EnumOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.EnumOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cEnumKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDataKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDataAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDataOptionItemParserRuleCall_5_0 = (RuleCall)cDataAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDataAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDataOptionItemParserRuleCall_6_1_0 = (RuleCall)cDataAssignment_6_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//EnumOption:
		//    "optionType:" "enum" ","
		//     "data:" "[" data+=OptionItem ("," data+=OptionItem)* "]"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"optionType:" "enum" ","
		// "data:" "[" data+=OptionItem ("," data+=OptionItem)* "]"
		public Group getGroup() { return cGroup; }
		
		//"optionType:"
		public Keyword getOptionTypeKeyword_0() { return cOptionTypeKeyword_0; }
		
		//"enum"
		public Keyword getEnumKeyword_1() { return cEnumKeyword_1; }
		
		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//"data:"
		public Keyword getDataKeyword_3() { return cDataKeyword_3; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_4() { return cLeftSquareBracketKeyword_4; }
		
		//data+=OptionItem
		public Assignment getDataAssignment_5() { return cDataAssignment_5; }
		
		//OptionItem
		public RuleCall getDataOptionItemParserRuleCall_5_0() { return cDataOptionItemParserRuleCall_5_0; }
		
		//("," data+=OptionItem)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//data+=OptionItem
		public Assignment getDataAssignment_6_1() { return cDataAssignment_6_1; }
		
		//OptionItem
		public RuleCall getDataOptionItemParserRuleCall_6_1_0() { return cDataOptionItemParserRuleCall_6_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_7() { return cRightSquareBracketKeyword_7; }
	}
	public class NumberOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.NumberOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOptionTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cNumberKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMinKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMinAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMinINTTerminalRuleCall_4_0 = (RuleCall)cMinAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cMaxKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cMaxAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cMaxINTTerminalRuleCall_7_0 = (RuleCall)cMaxAssignment_7.eContents().get(0);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRangeKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cRangeAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cRangeINTTerminalRuleCall_10_0 = (RuleCall)cRangeAssignment_10.eContents().get(0);
		
		//NumberOption:
		//    "optionType:" "number" ","
		//     "min:" min=INT ","
		//       "max:" max=INT ","
		//    "range:" range=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"optionType:" "number" ","
		// "min:" min=INT ","
		//   "max:" max=INT ","
		//"range:" range=INT
		public Group getGroup() { return cGroup; }
		
		//"optionType:"
		public Keyword getOptionTypeKeyword_0() { return cOptionTypeKeyword_0; }
		
		//"number"
		public Keyword getNumberKeyword_1() { return cNumberKeyword_1; }
		
		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//"min:"
		public Keyword getMinKeyword_3() { return cMinKeyword_3; }
		
		//min=INT
		public Assignment getMinAssignment_4() { return cMinAssignment_4; }
		
		//INT
		public RuleCall getMinINTTerminalRuleCall_4_0() { return cMinINTTerminalRuleCall_4_0; }
		
		//","
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//"max:"
		public Keyword getMaxKeyword_6() { return cMaxKeyword_6; }
		
		//max=INT
		public Assignment getMaxAssignment_7() { return cMaxAssignment_7; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_7_0() { return cMaxINTTerminalRuleCall_7_0; }
		
		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//"range:"
		public Keyword getRangeKeyword_9() { return cRangeKeyword_9; }
		
		//range=INT
		public Assignment getRangeAssignment_10() { return cRangeAssignment_10; }
		
		//INT
		public RuleCall getRangeINTTerminalRuleCall_10_0() { return cRangeINTTerminalRuleCall_10_0; }
	}
	public class FormInputSearchElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputSearch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cSEARCHKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cOptionsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftSquareBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDataAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDataOptionItemParserRuleCall_10_0 = (RuleCall)cDataAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cCommaKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cDataAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cDataOptionItemParserRuleCall_11_1_0 = (RuleCall)cDataAssignment_11_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//FormInputSearch:
		//    "name" ":" name=STRING ","
		//    "type" ":" "SEARCH" ","
		//    "options:" "[" data+=OptionItem ("," data+=OptionItem)* "]"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"name" ":" name=STRING ","
		//"type" ":" "SEARCH" ","
		//"options:" "[" data+=OptionItem ("," data+=OptionItem)* "]"
		public Group getGroup() { return cGroup; }
		
		//"name"
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"type"
		public Keyword getTypeKeyword_4() { return cTypeKeyword_4; }
		
		//":"
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }
		
		//"SEARCH"
		public Keyword getSEARCHKeyword_6() { return cSEARCHKeyword_6; }
		
		//","
		public Keyword getCommaKeyword_7() { return cCommaKeyword_7; }
		
		//"options:"
		public Keyword getOptionsKeyword_8() { return cOptionsKeyword_8; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_9() { return cLeftSquareBracketKeyword_9; }
		
		//data+=OptionItem
		public Assignment getDataAssignment_10() { return cDataAssignment_10; }
		
		//OptionItem
		public RuleCall getDataOptionItemParserRuleCall_10_0() { return cDataOptionItemParserRuleCall_10_0; }
		
		//("," data+=OptionItem)*
		public Group getGroup_11() { return cGroup_11; }
		
		//","
		public Keyword getCommaKeyword_11_0() { return cCommaKeyword_11_0; }
		
		//data+=OptionItem
		public Assignment getDataAssignment_11_1() { return cDataAssignment_11_1; }
		
		//OptionItem
		public RuleCall getDataOptionItemParserRuleCall_11_1_0() { return cDataOptionItemParserRuleCall_11_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_12() { return cRightSquareBracketKeyword_12; }
	}
	public class OptionItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.OptionItem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringOptionItemParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntOptionItemParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDataOptionItemParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//OptionItem:
		//    StringOptionItem | IntOptionItem | DataOptionItem
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//StringOptionItem | IntOptionItem | DataOptionItem
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StringOptionItem
		public RuleCall getStringOptionItemParserRuleCall_0() { return cStringOptionItemParserRuleCall_0; }
		
		//IntOptionItem
		public RuleCall getIntOptionItemParserRuleCall_1() { return cIntOptionItemParserRuleCall_1; }
		
		//DataOptionItem
		public RuleCall getDataOptionItemParserRuleCall_2() { return cDataOptionItemParserRuleCall_2; }
	}
	public class StringOptionItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.StringOptionItem");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringOptionItem:
		//    value=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}
	public class IntOptionItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.IntOptionItem");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntOptionItem:
		//    value=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	public class DataOptionItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.DataOptionItem");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueDataParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//DataOptionItem:
		//    value=Data
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=Data
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Data
		public RuleCall getValueDataParserRuleCall_0() { return cValueDataParserRuleCall_0; }
	}
	public class FormInputGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cGROUPKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cGroupInputsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cGroupInputsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cGroupInputsFormInputCrossReference_8_0 = (CrossReference)cGroupInputsAssignment_8.eContents().get(0);
		private final RuleCall cGroupInputsFormInputIDTerminalRuleCall_8_0_1 = (RuleCall)cGroupInputsFormInputCrossReference_8_0.eContents().get(1);
		
		//FormInputGroup:
		//    "name" ":" name=STRING ","
		//    "type:" "GROUP" ","
		//    "groupInputs:"  groupInputs=[FormInput]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"name" ":" name=STRING ","
		//"type:" "GROUP" ","
		//"groupInputs:"  groupInputs=[FormInput]
		public Group getGroup() { return cGroup; }
		
		//"name"
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"type:"
		public Keyword getTypeKeyword_4() { return cTypeKeyword_4; }
		
		//"GROUP"
		public Keyword getGROUPKeyword_5() { return cGROUPKeyword_5; }
		
		//","
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
		
		//"groupInputs:"
		public Keyword getGroupInputsKeyword_7() { return cGroupInputsKeyword_7; }
		
		//groupInputs=[FormInput]
		public Assignment getGroupInputsAssignment_8() { return cGroupInputsAssignment_8; }
		
		//[FormInput]
		public CrossReference getGroupInputsFormInputCrossReference_8_0() { return cGroupInputsFormInputCrossReference_8_0; }
		
		//ID
		public RuleCall getGroupInputsFormInputIDTerminalRuleCall_8_0_1() { return cGroupInputsFormInputIDTerminalRuleCall_8_0_1; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.Data");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringDataParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntDataParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Data:
		//    StringData | IntData;
		@Override public ParserRule getRule() { return rule; }
		
		//StringData | IntData
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StringData
		public RuleCall getStringDataParserRuleCall_0() { return cStringDataParserRuleCall_0; }
		
		//IntData
		public RuleCall getIntDataParserRuleCall_1() { return cIntDataParserRuleCall_1; }
	}
	public class StringDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.StringData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLabelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueSTRINGTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StringData:
		//    "{"
		//           "label:" label=STRING ","
		//        "value:" value=STRING
		//    "}";
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//       "label:" label=STRING ","
		//    "value:" value=STRING
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"label:"
		public Keyword getLabelKeyword_1() { return cLabelKeyword_1; }
		
		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"value:"
		public Keyword getValueKeyword_4() { return cValueKeyword_4; }
		
		//value=STRING
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_5_0() { return cValueSTRINGTerminalRuleCall_5_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class IntDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.IntData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLabelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueINTTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//IntData:
		//    "{"
		//           "label:" label=STRING ","
		//        "value:" value=INT
		//    "}";
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//       "label:" label=STRING ","
		//    "value:" value=INT
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"label:"
		public Keyword getLabelKeyword_1() { return cLabelKeyword_1; }
		
		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"value:"
		public Keyword getValueKeyword_4() { return cValueKeyword_4; }
		
		//value=INT
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_5_0() { return cValueINTTerminalRuleCall_5_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	public class InputTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.InputType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTEXTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTEXTTEXTKeyword_0_0 = (Keyword)cTEXTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCHECKBOXEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCHECKBOXCHECKBOXKeyword_1_0 = (Keyword)cCHECKBOXEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNUMBEREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNUMBERNUMBERKeyword_2_0 = (Keyword)cNUMBEREnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDATEEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDATEDATEKeyword_3_0 = (Keyword)cDATEEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cRANGEEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cRANGERANGEKeyword_4_0 = (Keyword)cRANGEEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cSELECTEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cSELECTSELECTKeyword_5_0 = (Keyword)cSELECTEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cSEARCHEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cSEARCHSEARCHKeyword_6_0 = (Keyword)cSEARCHEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cGROUPEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cGROUPGROUPKeyword_7_0 = (Keyword)cGROUPEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum InputType:
		//    TEXT | CHECKBOX | NUMBER | DATE
		//    | RANGE | SELECT | SEARCH | GROUP
		//;
		public EnumRule getRule() { return rule; }
		
		//TEXT | CHECKBOX | NUMBER | DATE
		//| RANGE | SELECT | SEARCH | GROUP
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//TEXT
		public EnumLiteralDeclaration getTEXTEnumLiteralDeclaration_0() { return cTEXTEnumLiteralDeclaration_0; }
		
		public Keyword getTEXTTEXTKeyword_0_0() { return cTEXTTEXTKeyword_0_0; }
		
		//CHECKBOX
		public EnumLiteralDeclaration getCHECKBOXEnumLiteralDeclaration_1() { return cCHECKBOXEnumLiteralDeclaration_1; }
		
		public Keyword getCHECKBOXCHECKBOXKeyword_1_0() { return cCHECKBOXCHECKBOXKeyword_1_0; }
		
		//NUMBER
		public EnumLiteralDeclaration getNUMBEREnumLiteralDeclaration_2() { return cNUMBEREnumLiteralDeclaration_2; }
		
		public Keyword getNUMBERNUMBERKeyword_2_0() { return cNUMBERNUMBERKeyword_2_0; }
		
		//DATE
		public EnumLiteralDeclaration getDATEEnumLiteralDeclaration_3() { return cDATEEnumLiteralDeclaration_3; }
		
		public Keyword getDATEDATEKeyword_3_0() { return cDATEDATEKeyword_3_0; }
		
		//RANGE
		public EnumLiteralDeclaration getRANGEEnumLiteralDeclaration_4() { return cRANGEEnumLiteralDeclaration_4; }
		
		public Keyword getRANGERANGEKeyword_4_0() { return cRANGERANGEKeyword_4_0; }
		
		//SELECT
		public EnumLiteralDeclaration getSELECTEnumLiteralDeclaration_5() { return cSELECTEnumLiteralDeclaration_5; }
		
		public Keyword getSELECTSELECTKeyword_5_0() { return cSELECTSELECTKeyword_5_0; }
		
		//SEARCH
		public EnumLiteralDeclaration getSEARCHEnumLiteralDeclaration_6() { return cSEARCHEnumLiteralDeclaration_6; }
		
		public Keyword getSEARCHSEARCHKeyword_6_0() { return cSEARCHSEARCHKeyword_6_0; }
		
		//GROUP
		public EnumLiteralDeclaration getGROUPEnumLiteralDeclaration_7() { return cGROUPEnumLiteralDeclaration_7; }
		
		public Keyword getGROUPGROUPKeyword_7_0() { return cGROUPGROUPKeyword_7_0; }
	}
	public class LayoutElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.Layout");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cHorizontalEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cHorizontalHorizontalKeyword_0_0 = (Keyword)cHorizontalEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cVerticalEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cVerticalVerticalKeyword_1_0 = (Keyword)cVerticalEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Layout:
		//    horizontal|vertical ;
		public EnumRule getRule() { return rule; }
		
		//horizontal|vertical
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//horizontal
		public EnumLiteralDeclaration getHorizontalEnumLiteralDeclaration_0() { return cHorizontalEnumLiteralDeclaration_0; }
		
		public Keyword getHorizontalHorizontalKeyword_0_0() { return cHorizontalHorizontalKeyword_0_0; }
		
		//vertical
		public EnumLiteralDeclaration getVerticalEnumLiteralDeclaration_1() { return cVerticalEnumLiteralDeclaration_1; }
		
		public Keyword getVerticalVerticalKeyword_1_0() { return cVerticalVerticalKeyword_1_0; }
	}
	
	private final ModelElements pModel;
	private final FormLayoutElements pFormLayout;
	private final FormInputElements pFormInput;
	private final FormInputBasicElements pFormInputBasic;
	private final InputTypeElements eInputType;
	private final FormInputRangeElements pFormInputRange;
	private final FormInputSelectElements pFormInputSelect;
	private final OptionElements pOption;
	private final DataOptionElements pDataOption;
	private final EnumOptionElements pEnumOption;
	private final NumberOptionElements pNumberOption;
	private final FormInputSearchElements pFormInputSearch;
	private final OptionItemElements pOptionItem;
	private final StringOptionItemElements pStringOptionItem;
	private final IntOptionItemElements pIntOptionItem;
	private final DataOptionItemElements pDataOptionItem;
	private final FormInputGroupElements pFormInputGroup;
	private final DataElements pData;
	private final StringDataElements pStringData;
	private final IntDataElements pIntData;
	private final LayoutElements eLayout;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public VFormDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pFormLayout = new FormLayoutElements();
		this.pFormInput = new FormInputElements();
		this.pFormInputBasic = new FormInputBasicElements();
		this.eInputType = new InputTypeElements();
		this.pFormInputRange = new FormInputRangeElements();
		this.pFormInputSelect = new FormInputSelectElements();
		this.pOption = new OptionElements();
		this.pDataOption = new DataOptionElements();
		this.pEnumOption = new EnumOptionElements();
		this.pNumberOption = new NumberOptionElements();
		this.pFormInputSearch = new FormInputSearchElements();
		this.pOptionItem = new OptionItemElements();
		this.pStringOptionItem = new StringOptionItemElements();
		this.pIntOptionItem = new IntOptionItemElements();
		this.pDataOptionItem = new DataOptionItemElements();
		this.pFormInputGroup = new FormInputGroupElements();
		this.pData = new DataElements();
		this.pStringData = new StringDataElements();
		this.pIntData = new IntDataElements();
		this.eLayout = new LayoutElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("cafev.vform.VFormDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    "formLayout:" formLayout=FormLayout ","
	//    "formInputs:" "["
	//        (formInput+=FormInput*)
	//    "]"
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//FormLayout:
	//    layout=Layout;
	public FormLayoutElements getFormLayoutAccess() {
		return pFormLayout;
	}
	
	public ParserRule getFormLayoutRule() {
		return getFormLayoutAccess().getRule();
	}
	
	//FormInput:
	//    FormInputBasic | FormInputRange | FormInputSelect| FormInputSearch | FormInputGroup
	//;
	public FormInputElements getFormInputAccess() {
		return pFormInput;
	}
	
	public ParserRule getFormInputRule() {
		return getFormInputAccess().getRule();
	}
	
	//FormInputBasic:
	//    "name" ":" name=STRING
	//    "type" ":" type=InputType
	//;
	public FormInputBasicElements getFormInputBasicAccess() {
		return pFormInputBasic;
	}
	
	public ParserRule getFormInputBasicRule() {
		return getFormInputBasicAccess().getRule();
	}
	
	//enum InputType:
	//    TEXT | CHECKBOX | NUMBER | DATE
	//    | RANGE | SELECT | SEARCH | GROUP
	//;
	public InputTypeElements getInputTypeAccess() {
		return eInputType;
	}
	
	public EnumRule getInputTypeRule() {
		return getInputTypeAccess().getRule();
	}
	
	//FormInputRange:
	//    "name" ":" name=STRING ","
	//    "type" ":" "RANGE" ","
	//    "min:" min=INT ","
	//    "max:" max=INT
	//;
	public FormInputRangeElements getFormInputRangeAccess() {
		return pFormInputRange;
	}
	
	public ParserRule getFormInputRangeRule() {
		return getFormInputRangeAccess().getRule();
	}
	
	//FormInputSelect:
	//    "name" ":" name=STRING ","
	//    "type" ":" "SELECT" ","
	//    "options:" "{" option=Option "}"
	//;
	public FormInputSelectElements getFormInputSelectAccess() {
		return pFormInputSelect;
	}
	
	public ParserRule getFormInputSelectRule() {
		return getFormInputSelectAccess().getRule();
	}
	
	//Option:
	//    DataOption | EnumOption | NumberOption
	//;
	public OptionElements getOptionAccess() {
		return pOption;
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}
	
	//DataOption:
	//    "optionType:" "data" ","
	//     "data:" "[" data+=Data ("," data+=Data)* "]"
	//;
	public DataOptionElements getDataOptionAccess() {
		return pDataOption;
	}
	
	public ParserRule getDataOptionRule() {
		return getDataOptionAccess().getRule();
	}
	
	//EnumOption:
	//    "optionType:" "enum" ","
	//     "data:" "[" data+=OptionItem ("," data+=OptionItem)* "]"
	//;
	public EnumOptionElements getEnumOptionAccess() {
		return pEnumOption;
	}
	
	public ParserRule getEnumOptionRule() {
		return getEnumOptionAccess().getRule();
	}
	
	//NumberOption:
	//    "optionType:" "number" ","
	//     "min:" min=INT ","
	//       "max:" max=INT ","
	//    "range:" range=INT
	//;
	public NumberOptionElements getNumberOptionAccess() {
		return pNumberOption;
	}
	
	public ParserRule getNumberOptionRule() {
		return getNumberOptionAccess().getRule();
	}
	
	//FormInputSearch:
	//    "name" ":" name=STRING ","
	//    "type" ":" "SEARCH" ","
	//    "options:" "[" data+=OptionItem ("," data+=OptionItem)* "]"
	//;
	public FormInputSearchElements getFormInputSearchAccess() {
		return pFormInputSearch;
	}
	
	public ParserRule getFormInputSearchRule() {
		return getFormInputSearchAccess().getRule();
	}
	
	//OptionItem:
	//    StringOptionItem | IntOptionItem | DataOptionItem
	//;
	public OptionItemElements getOptionItemAccess() {
		return pOptionItem;
	}
	
	public ParserRule getOptionItemRule() {
		return getOptionItemAccess().getRule();
	}
	
	//StringOptionItem:
	//    value=STRING
	//;
	public StringOptionItemElements getStringOptionItemAccess() {
		return pStringOptionItem;
	}
	
	public ParserRule getStringOptionItemRule() {
		return getStringOptionItemAccess().getRule();
	}
	
	//IntOptionItem:
	//    value=INT
	//;
	public IntOptionItemElements getIntOptionItemAccess() {
		return pIntOptionItem;
	}
	
	public ParserRule getIntOptionItemRule() {
		return getIntOptionItemAccess().getRule();
	}
	
	//DataOptionItem:
	//    value=Data
	//;
	public DataOptionItemElements getDataOptionItemAccess() {
		return pDataOptionItem;
	}
	
	public ParserRule getDataOptionItemRule() {
		return getDataOptionItemAccess().getRule();
	}
	
	//FormInputGroup:
	//    "name" ":" name=STRING ","
	//    "type:" "GROUP" ","
	//    "groupInputs:"  groupInputs=[FormInput]
	//;
	public FormInputGroupElements getFormInputGroupAccess() {
		return pFormInputGroup;
	}
	
	public ParserRule getFormInputGroupRule() {
		return getFormInputGroupAccess().getRule();
	}
	
	//Data:
	//    StringData | IntData;
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//StringData:
	//    "{"
	//           "label:" label=STRING ","
	//        "value:" value=STRING
	//    "}";
	public StringDataElements getStringDataAccess() {
		return pStringData;
	}
	
	public ParserRule getStringDataRule() {
		return getStringDataAccess().getRule();
	}
	
	//IntData:
	//    "{"
	//           "label:" label=STRING ","
	//        "value:" value=INT
	//    "}";
	public IntDataElements getIntDataAccess() {
		return pIntData;
	}
	
	public ParserRule getIntDataRule() {
		return getIntDataAccess().getRule();
	}
	
	//enum Layout:
	//    horizontal|vertical ;
	public LayoutElements getLayoutAccess() {
		return eLayout;
	}
	
	public EnumRule getLayoutRule() {
		return getLayoutAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
