/*
 * generated by Xtext 2.28.0
 */
package cafev.vform.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class VFormDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFormLayoutKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFormLayoutAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFormLayoutFormLayoutParserRuleCall_2_0 = (RuleCall)cFormLayoutAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cFormInputsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFormInputAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFormInputFormInputParserRuleCall_6_0 = (RuleCall)cFormInputAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cFormInputAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cFormInputFormInputParserRuleCall_7_1_0 = (RuleCall)cFormInputAssignment_7_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Model:
		//"{"
		//    "\"formLayout\":" formLayout=FormLayout ","
		//    "\"formInputs\":" "["formInput+=FormInput ("," formInput+=FormInput)*"]"
		//"}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    "\"formLayout\":" formLayout=FormLayout ","
		//    "\"formInputs\":" "["formInput+=FormInput ("," formInput+=FormInput)*"]"
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"\"formLayout\":"
		public Keyword getFormLayoutKeyword_1() { return cFormLayoutKeyword_1; }
		
		//formLayout=FormLayout
		public Assignment getFormLayoutAssignment_2() { return cFormLayoutAssignment_2; }
		
		//FormLayout
		public RuleCall getFormLayoutFormLayoutParserRuleCall_2_0() { return cFormLayoutFormLayoutParserRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"\"formInputs\":"
		public Keyword getFormInputsKeyword_4() { return cFormInputsKeyword_4; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_5() { return cLeftSquareBracketKeyword_5; }
		
		//formInput+=FormInput
		public Assignment getFormInputAssignment_6() { return cFormInputAssignment_6; }
		
		//FormInput
		public RuleCall getFormInputFormInputParserRuleCall_6_0() { return cFormInputFormInputParserRuleCall_6_0; }
		
		//("," formInput+=FormInput)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//formInput+=FormInput
		public Assignment getFormInputAssignment_7_1() { return cFormInputAssignment_7_1; }
		
		//FormInput
		public RuleCall getFormInputFormInputParserRuleCall_7_1_0() { return cFormInputFormInputParserRuleCall_7_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_8() { return cRightSquareBracketKeyword_8; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class FormLayoutElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormLayout");
		private final Assignment cLayoutAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cLayoutLAYOUTTerminalRuleCall_0 = (RuleCall)cLayoutAssignment.eContents().get(0);
		
		//FormLayout:
		//    layout=LAYOUT;
		@Override public ParserRule getRule() { return rule; }
		
		//layout=LAYOUT
		public Assignment getLayoutAssignment() { return cLayoutAssignment; }
		
		//LAYOUT
		public RuleCall getLayoutLAYOUTTerminalRuleCall_0() { return cLayoutLAYOUTTerminalRuleCall_0; }
	}
	public class FormInputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInput");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFormInputBasicParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFormInputRangeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFormInputSelectParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFormInputSearchParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cFormInputGroupParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//FormInput:
		//    FormInputBasic | FormInputRange | FormInputSelect| FormInputSearch | FormInputGroup
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//FormInputBasic | FormInputRange | FormInputSelect| FormInputSearch | FormInputGroup
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FormInputBasic
		public RuleCall getFormInputBasicParserRuleCall_0() { return cFormInputBasicParserRuleCall_0; }
		
		//FormInputRange
		public RuleCall getFormInputRangeParserRuleCall_1() { return cFormInputRangeParserRuleCall_1; }
		
		//FormInputSelect
		public RuleCall getFormInputSelectParserRuleCall_2() { return cFormInputSelectParserRuleCall_2; }
		
		//FormInputSearch
		public RuleCall getFormInputSearchParserRuleCall_3() { return cFormInputSearchParserRuleCall_3; }
		
		//FormInputGroup
		public RuleCall getFormInputGroupParserRuleCall_4() { return cFormInputGroupParserRuleCall_4; }
	}
	public class FormInputBasicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputBasic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cInputNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cInputTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTypeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTypeBASICINPUTTerminalRuleCall_7_0 = (RuleCall)cTypeAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//FormInputBasic:
		//"{"
		//    "\"inputName\"" ":" name=STRING ","
		//    "\"inputType\"" ":" type=BASICINPUT
		//"}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    "\"inputName\"" ":" name=STRING ","
		//    "\"inputType\"" ":" type=BASICINPUT
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"\"inputName\""
		public Keyword getInputNameKeyword_1() { return cInputNameKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//name=STRING
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_3_0() { return cNameSTRINGTerminalRuleCall_3_0; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//"\"inputType\""
		public Keyword getInputTypeKeyword_5() { return cInputTypeKeyword_5; }
		
		//":"
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//type=BASICINPUT
		public Assignment getTypeAssignment_7() { return cTypeAssignment_7; }
		
		//BASICINPUT
		public RuleCall getTypeBASICINPUTTerminalRuleCall_7_0() { return cTypeBASICINPUTTerminalRuleCall_7_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class FormInputRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cInputNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cInputTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRangeKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cMinKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMinAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMinINTTerminalRuleCall_11_0 = (RuleCall)cMinAssignment_11.eContents().get(0);
		private final Keyword cCommaKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cMaxKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cColonKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Assignment cMaxAssignment_15 = (Assignment)cGroup.eContents().get(15);
		private final RuleCall cMaxINTTerminalRuleCall_15_0 = (RuleCall)cMaxAssignment_15.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//FormInputRange:
		//"{"
		//    "\"inputName\"" ":" name=STRING ","
		//    "\"inputType\"" ":" "\"range\"" ","
		//    "\"min\"" ":" min=INT ","
		//    "\"max\"" ":" max=INT
		//"}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    "\"inputName\"" ":" name=STRING ","
		//    "\"inputType\"" ":" "\"range\"" ","
		//    "\"min\"" ":" min=INT ","
		//    "\"max\"" ":" max=INT
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"\"inputName\""
		public Keyword getInputNameKeyword_1() { return cInputNameKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//name=STRING
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_3_0() { return cNameSTRINGTerminalRuleCall_3_0; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//"\"inputType\""
		public Keyword getInputTypeKeyword_5() { return cInputTypeKeyword_5; }
		
		//":"
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//"\"range\""
		public Keyword getRangeKeyword_7() { return cRangeKeyword_7; }
		
		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//"\"min\""
		public Keyword getMinKeyword_9() { return cMinKeyword_9; }
		
		//":"
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//min=INT
		public Assignment getMinAssignment_11() { return cMinAssignment_11; }
		
		//INT
		public RuleCall getMinINTTerminalRuleCall_11_0() { return cMinINTTerminalRuleCall_11_0; }
		
		//","
		public Keyword getCommaKeyword_12() { return cCommaKeyword_12; }
		
		//"\"max\""
		public Keyword getMaxKeyword_13() { return cMaxKeyword_13; }
		
		//":"
		public Keyword getColonKeyword_14() { return cColonKeyword_14; }
		
		//max=INT
		public Assignment getMaxAssignment_15() { return cMaxAssignment_15; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_15_0() { return cMaxINTTerminalRuleCall_15_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}
	public class FormInputSelectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputSelect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cInputNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cInputTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cSelectKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cOptionsKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cOptionAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cOptionOptionParserRuleCall_11_0 = (RuleCall)cOptionAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//FormInputSelect:
		//"{"
		//    "\"inputName\"" ":" name=STRING ","
		//    "\"inputType\"" ":" "\"select\"" ","
		//     "\"options\"" ":"  option=Option
		//"}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    "\"inputName\"" ":" name=STRING ","
		//    "\"inputType\"" ":" "\"select\"" ","
		//     "\"options\"" ":"  option=Option
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"\"inputName\""
		public Keyword getInputNameKeyword_1() { return cInputNameKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//name=STRING
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_3_0() { return cNameSTRINGTerminalRuleCall_3_0; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//"\"inputType\""
		public Keyword getInputTypeKeyword_5() { return cInputTypeKeyword_5; }
		
		//":"
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//"\"select\""
		public Keyword getSelectKeyword_7() { return cSelectKeyword_7; }
		
		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//"\"options\""
		public Keyword getOptionsKeyword_9() { return cOptionsKeyword_9; }
		
		//":"
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//option=Option
		public Assignment getOptionAssignment_11() { return cOptionAssignment_11; }
		
		//Option
		public RuleCall getOptionOptionParserRuleCall_11_0() { return cOptionOptionParserRuleCall_11_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class OptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.Option");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDataOptionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEnumOptionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNumberOptionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Option:
		//    DataOption | EnumOption | NumberOption
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//DataOption | EnumOption | NumberOption
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DataOption
		public RuleCall getDataOptionParserRuleCall_0() { return cDataOptionParserRuleCall_0; }
		
		//EnumOption
		public RuleCall getEnumOptionParserRuleCall_1() { return cEnumOptionParserRuleCall_1; }
		
		//NumberOption
		public RuleCall getNumberOptionParserRuleCall_2() { return cNumberOptionParserRuleCall_2; }
	}
	public class DataOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.DataOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cOptionTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDataKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDataAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDataDataParserRuleCall_8_0 = (RuleCall)cDataAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cDataAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cDataDataParserRuleCall_9_1_0 = (RuleCall)cDataAssignment_9_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//DataOption:
		//"{"
		//    "\"optionType\"" ":" "\"data\"" ","
		//     "\"data\"" ":" "[" data+=Data ("," data+=Data)* "]"
		//"}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    "\"optionType\"" ":" "\"data\"" ","
		//     "\"data\"" ":" "[" data+=Data ("," data+=Data)* "]"
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"\"optionType\""
		public Keyword getOptionTypeKeyword_1() { return cOptionTypeKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//"\"data\""
		public Keyword getDataKeyword_3() { return cDataKeyword_3; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//"\"data\""
		public Keyword getDataKeyword_5() { return cDataKeyword_5; }
		
		//":"
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_7() { return cLeftSquareBracketKeyword_7; }
		
		//data+=Data
		public Assignment getDataAssignment_8() { return cDataAssignment_8; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_8_0() { return cDataDataParserRuleCall_8_0; }
		
		//("," data+=Data)*
		public Group getGroup_9() { return cGroup_9; }
		
		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }
		
		//data+=Data
		public Assignment getDataAssignment_9_1() { return cDataAssignment_9_1; }
		
		//Data
		public RuleCall getDataDataParserRuleCall_9_1_0() { return cDataDataParserRuleCall_9_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class EnumOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.EnumOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cOptionTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cEnumKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftSquareBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDataAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDataOptionItemParserRuleCall_8_0 = (RuleCall)cDataAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCommaKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cDataAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cDataOptionItemParserRuleCall_9_1_0 = (RuleCall)cDataAssignment_9_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//EnumOption:
		//"{"
		//    "\"optionType\"" ":" "\"enum\"" ","
		//     "\"data\"" ":" "[" data+=OptionItem ("," data+=OptionItem)* "]"
		//"}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    "\"optionType\"" ":" "\"enum\"" ","
		//     "\"data\"" ":" "[" data+=OptionItem ("," data+=OptionItem)* "]"
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"\"optionType\""
		public Keyword getOptionTypeKeyword_1() { return cOptionTypeKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//"\"enum\""
		public Keyword getEnumKeyword_3() { return cEnumKeyword_3; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//"\"data\""
		public Keyword getDataKeyword_5() { return cDataKeyword_5; }
		
		//":"
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_7() { return cLeftSquareBracketKeyword_7; }
		
		//data+=OptionItem
		public Assignment getDataAssignment_8() { return cDataAssignment_8; }
		
		//OptionItem
		public RuleCall getDataOptionItemParserRuleCall_8_0() { return cDataOptionItemParserRuleCall_8_0; }
		
		//("," data+=OptionItem)*
		public Group getGroup_9() { return cGroup_9; }
		
		//","
		public Keyword getCommaKeyword_9_0() { return cCommaKeyword_9_0; }
		
		//data+=OptionItem
		public Assignment getDataAssignment_9_1() { return cDataAssignment_9_1; }
		
		//OptionItem
		public RuleCall getDataOptionItemParserRuleCall_9_1_0() { return cDataOptionItemParserRuleCall_9_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_10() { return cRightSquareBracketKeyword_10; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class NumberOptionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.NumberOption");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cOptionTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNumberKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cMinKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cMinAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cMinINTTerminalRuleCall_7_0 = (RuleCall)cMinAssignment_7.eContents().get(0);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cMaxKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMaxAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMaxINTTerminalRuleCall_11_0 = (RuleCall)cMaxAssignment_11.eContents().get(0);
		private final Keyword cRangeKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cColonKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cRangeAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cRangeINTTerminalRuleCall_14_0 = (RuleCall)cRangeAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//NumberOption:
		//"{"
		//    "\"optionType\"" ":" "\"number\"" ","
		//    "\"min\"" ":" min=INT ","
		//    "\"max\"" ":" max=INT
		//    "\"range\"" ":" range=INT
		//"}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    "\"optionType\"" ":" "\"number\"" ","
		//    "\"min\"" ":" min=INT ","
		//    "\"max\"" ":" max=INT
		//    "\"range\"" ":" range=INT
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"\"optionType\""
		public Keyword getOptionTypeKeyword_1() { return cOptionTypeKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//"\"number\""
		public Keyword getNumberKeyword_3() { return cNumberKeyword_3; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//"\"min\""
		public Keyword getMinKeyword_5() { return cMinKeyword_5; }
		
		//":"
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//min=INT
		public Assignment getMinAssignment_7() { return cMinAssignment_7; }
		
		//INT
		public RuleCall getMinINTTerminalRuleCall_7_0() { return cMinINTTerminalRuleCall_7_0; }
		
		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//"\"max\""
		public Keyword getMaxKeyword_9() { return cMaxKeyword_9; }
		
		//":"
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//max=INT
		public Assignment getMaxAssignment_11() { return cMaxAssignment_11; }
		
		//INT
		public RuleCall getMaxINTTerminalRuleCall_11_0() { return cMaxINTTerminalRuleCall_11_0; }
		
		//"\"range\""
		public Keyword getRangeKeyword_12() { return cRangeKeyword_12; }
		
		//":"
		public Keyword getColonKeyword_13() { return cColonKeyword_13; }
		
		//range=INT
		public Assignment getRangeAssignment_14() { return cRangeAssignment_14; }
		
		//INT
		public RuleCall getRangeINTTerminalRuleCall_14_0() { return cRangeINTTerminalRuleCall_14_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class FormInputSearchElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputSearch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cInputNameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameSTRINGTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cInputTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cSearchKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cDataKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftSquareBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cDataAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cDataOptionItemParserRuleCall_12_0 = (RuleCall)cDataAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cDataAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cDataOptionItemParserRuleCall_13_1_0 = (RuleCall)cDataAssignment_13_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//FormInputSearch:
		//"{"
		//    "\"inputName\"" ":" name=STRING ","
		//    "\"inputType\"" ":" "\"search\"" ","
		//     "\"data\"" ":"  "[" data+=OptionItem ("," data+=OptionItem)* "]"
		//"}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//    "\"inputName\"" ":" name=STRING ","
		//    "\"inputType\"" ":" "\"search\"" ","
		//     "\"data\"" ":"  "[" data+=OptionItem ("," data+=OptionItem)* "]"
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"\"inputName\""
		public Keyword getInputNameKeyword_1() { return cInputNameKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//name=STRING
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_3_0() { return cNameSTRINGTerminalRuleCall_3_0; }
		
		//","
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//"\"inputType\""
		public Keyword getInputTypeKeyword_5() { return cInputTypeKeyword_5; }
		
		//":"
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//"\"search\""
		public Keyword getSearchKeyword_7() { return cSearchKeyword_7; }
		
		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//"\"data\""
		public Keyword getDataKeyword_9() { return cDataKeyword_9; }
		
		//":"
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_11() { return cLeftSquareBracketKeyword_11; }
		
		//data+=OptionItem
		public Assignment getDataAssignment_12() { return cDataAssignment_12; }
		
		//OptionItem
		public RuleCall getDataOptionItemParserRuleCall_12_0() { return cDataOptionItemParserRuleCall_12_0; }
		
		//("," data+=OptionItem)*
		public Group getGroup_13() { return cGroup_13; }
		
		//","
		public Keyword getCommaKeyword_13_0() { return cCommaKeyword_13_0; }
		
		//data+=OptionItem
		public Assignment getDataAssignment_13_1() { return cDataAssignment_13_1; }
		
		//OptionItem
		public RuleCall getDataOptionItemParserRuleCall_13_1_0() { return cDataOptionItemParserRuleCall_13_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_14() { return cRightSquareBracketKeyword_14; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class OptionItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.OptionItem");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringOptionItemParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntOptionItemParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDataOptionItemParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//OptionItem:
		//    StringOptionItem | IntOptionItem | DataOptionItem
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//StringOptionItem | IntOptionItem | DataOptionItem
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StringOptionItem
		public RuleCall getStringOptionItemParserRuleCall_0() { return cStringOptionItemParserRuleCall_0; }
		
		//IntOptionItem
		public RuleCall getIntOptionItemParserRuleCall_1() { return cIntOptionItemParserRuleCall_1; }
		
		//DataOptionItem
		public RuleCall getDataOptionItemParserRuleCall_2() { return cDataOptionItemParserRuleCall_2; }
	}
	public class StringOptionItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.StringOptionItem");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueSTRINGTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//StringOptionItem:
		//    value=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=STRING
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_0() { return cValueSTRINGTerminalRuleCall_0; }
	}
	public class IntOptionItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.IntOptionItem");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueINTTerminalRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntOptionItem:
		//    value=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=INT
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_0() { return cValueINTTerminalRuleCall_0; }
	}
	public class DataOptionItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.DataOptionItem");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueDataParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//DataOptionItem:
		//    value=Data
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//value=Data
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Data
		public RuleCall getValueDataParserRuleCall_0() { return cValueDataParserRuleCall_0; }
	}
	public class FormInputGroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.FormInputGroup");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameSTRINGTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cGROUPKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cGroupInputsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cGroupInputsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final CrossReference cGroupInputsFormInputCrossReference_8_0 = (CrossReference)cGroupInputsAssignment_8.eContents().get(0);
		private final RuleCall cGroupInputsFormInputIDTerminalRuleCall_8_0_1 = (RuleCall)cGroupInputsFormInputCrossReference_8_0.eContents().get(1);
		
		//FormInputGroup:
		//    "name" ":" name=STRING ","
		//    "type:" "GROUP" ","
		//    "groupInputs:"  groupInputs=[FormInput]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"name" ":" name=STRING ","
		//"type:" "GROUP" ","
		//"groupInputs:"  groupInputs=[FormInput]
		public Group getGroup() { return cGroup; }
		
		//"name"
		public Keyword getNameKeyword_0() { return cNameKeyword_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//name=STRING
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_2_0() { return cNameSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"type:"
		public Keyword getTypeKeyword_4() { return cTypeKeyword_4; }
		
		//"GROUP"
		public Keyword getGROUPKeyword_5() { return cGROUPKeyword_5; }
		
		//","
		public Keyword getCommaKeyword_6() { return cCommaKeyword_6; }
		
		//"groupInputs:"
		public Keyword getGroupInputsKeyword_7() { return cGroupInputsKeyword_7; }
		
		//groupInputs=[FormInput]
		public Assignment getGroupInputsAssignment_8() { return cGroupInputsAssignment_8; }
		
		//[FormInput]
		public CrossReference getGroupInputsFormInputCrossReference_8_0() { return cGroupInputsFormInputCrossReference_8_0; }
		
		//ID
		public RuleCall getGroupInputsFormInputIDTerminalRuleCall_8_0_1() { return cGroupInputsFormInputIDTerminalRuleCall_8_0_1; }
	}
	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.Data");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStringDataParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntDataParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Data:
		//    StringData | IntData;
		@Override public ParserRule getRule() { return rule; }
		
		//StringData | IntData
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//StringData
		public RuleCall getStringDataParserRuleCall_0() { return cStringDataParserRuleCall_0; }
		
		//IntData
		public RuleCall getIntDataParserRuleCall_1() { return cIntDataParserRuleCall_1; }
	}
	public class StringDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.StringData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLabelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueSTRINGTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//StringData:
		//    "{"
		//           "label:" label=STRING ","
		//        "value:" value=STRING
		//    "}";
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//       "label:" label=STRING ","
		//    "value:" value=STRING
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"label:"
		public Keyword getLabelKeyword_1() { return cLabelKeyword_1; }
		
		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"value:"
		public Keyword getValueKeyword_4() { return cValueKeyword_4; }
		
		//value=STRING
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_5_0() { return cValueSTRINGTerminalRuleCall_5_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class IntDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.IntData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLabelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLabelAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_2_0 = (RuleCall)cLabelAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cValueKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueINTTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//IntData:
		//    "{"
		//           "label:" label=STRING ","
		//        "value:" value=INT
		//    "}";
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		//       "label:" label=STRING ","
		//    "value:" value=INT
		//"}"
		public Group getGroup() { return cGroup; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }
		
		//"label:"
		public Keyword getLabelKeyword_1() { return cLabelKeyword_1; }
		
		//label=STRING
		public Assignment getLabelAssignment_2() { return cLabelAssignment_2; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_2_0() { return cLabelSTRINGTerminalRuleCall_2_0; }
		
		//","
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//"value:"
		public Keyword getValueKeyword_4() { return cValueKeyword_4; }
		
		//value=INT
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_5_0() { return cValueINTTerminalRuleCall_5_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final ModelElements pModel;
	private final FormLayoutElements pFormLayout;
	private final FormInputElements pFormInput;
	private final FormInputBasicElements pFormInputBasic;
	private final FormInputRangeElements pFormInputRange;
	private final FormInputSelectElements pFormInputSelect;
	private final OptionElements pOption;
	private final DataOptionElements pDataOption;
	private final EnumOptionElements pEnumOption;
	private final NumberOptionElements pNumberOption;
	private final FormInputSearchElements pFormInputSearch;
	private final OptionItemElements pOptionItem;
	private final StringOptionItemElements pStringOptionItem;
	private final IntOptionItemElements pIntOptionItem;
	private final DataOptionItemElements pDataOptionItem;
	private final FormInputGroupElements pFormInputGroup;
	private final DataElements pData;
	private final StringDataElements pStringData;
	private final IntDataElements pIntData;
	private final TerminalRule tLAYOUT;
	private final TerminalRule tBASICINPUT;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public VFormDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pFormLayout = new FormLayoutElements();
		this.pFormInput = new FormInputElements();
		this.pFormInputBasic = new FormInputBasicElements();
		this.pFormInputRange = new FormInputRangeElements();
		this.pFormInputSelect = new FormInputSelectElements();
		this.pOption = new OptionElements();
		this.pDataOption = new DataOptionElements();
		this.pEnumOption = new EnumOptionElements();
		this.pNumberOption = new NumberOptionElements();
		this.pFormInputSearch = new FormInputSearchElements();
		this.pOptionItem = new OptionItemElements();
		this.pStringOptionItem = new StringOptionItemElements();
		this.pIntOptionItem = new IntOptionItemElements();
		this.pDataOptionItem = new DataOptionItemElements();
		this.pFormInputGroup = new FormInputGroupElements();
		this.pData = new DataElements();
		this.pStringData = new StringDataElements();
		this.pIntData = new IntDataElements();
		this.tLAYOUT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.LAYOUT");
		this.tBASICINPUT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "cafev.vform.VFormDsl.BASICINPUT");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("cafev.vform.VFormDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//"{"
	//    "\"formLayout\":" formLayout=FormLayout ","
	//    "\"formInputs\":" "["formInput+=FormInput ("," formInput+=FormInput)*"]"
	//"}"
	//;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//FormLayout:
	//    layout=LAYOUT;
	public FormLayoutElements getFormLayoutAccess() {
		return pFormLayout;
	}
	
	public ParserRule getFormLayoutRule() {
		return getFormLayoutAccess().getRule();
	}
	
	//FormInput:
	//    FormInputBasic | FormInputRange | FormInputSelect| FormInputSearch | FormInputGroup
	//;
	public FormInputElements getFormInputAccess() {
		return pFormInput;
	}
	
	public ParserRule getFormInputRule() {
		return getFormInputAccess().getRule();
	}
	
	//FormInputBasic:
	//"{"
	//    "\"inputName\"" ":" name=STRING ","
	//    "\"inputType\"" ":" type=BASICINPUT
	//"}"
	//;
	public FormInputBasicElements getFormInputBasicAccess() {
		return pFormInputBasic;
	}
	
	public ParserRule getFormInputBasicRule() {
		return getFormInputBasicAccess().getRule();
	}
	
	//FormInputRange:
	//"{"
	//    "\"inputName\"" ":" name=STRING ","
	//    "\"inputType\"" ":" "\"range\"" ","
	//    "\"min\"" ":" min=INT ","
	//    "\"max\"" ":" max=INT
	//"}"
	//;
	public FormInputRangeElements getFormInputRangeAccess() {
		return pFormInputRange;
	}
	
	public ParserRule getFormInputRangeRule() {
		return getFormInputRangeAccess().getRule();
	}
	
	//FormInputSelect:
	//"{"
	//    "\"inputName\"" ":" name=STRING ","
	//    "\"inputType\"" ":" "\"select\"" ","
	//     "\"options\"" ":"  option=Option
	//"}"
	//;
	public FormInputSelectElements getFormInputSelectAccess() {
		return pFormInputSelect;
	}
	
	public ParserRule getFormInputSelectRule() {
		return getFormInputSelectAccess().getRule();
	}
	
	//Option:
	//    DataOption | EnumOption | NumberOption
	//;
	public OptionElements getOptionAccess() {
		return pOption;
	}
	
	public ParserRule getOptionRule() {
		return getOptionAccess().getRule();
	}
	
	//DataOption:
	//"{"
	//    "\"optionType\"" ":" "\"data\"" ","
	//     "\"data\"" ":" "[" data+=Data ("," data+=Data)* "]"
	//"}"
	//;
	public DataOptionElements getDataOptionAccess() {
		return pDataOption;
	}
	
	public ParserRule getDataOptionRule() {
		return getDataOptionAccess().getRule();
	}
	
	//EnumOption:
	//"{"
	//    "\"optionType\"" ":" "\"enum\"" ","
	//     "\"data\"" ":" "[" data+=OptionItem ("," data+=OptionItem)* "]"
	//"}"
	//;
	public EnumOptionElements getEnumOptionAccess() {
		return pEnumOption;
	}
	
	public ParserRule getEnumOptionRule() {
		return getEnumOptionAccess().getRule();
	}
	
	//NumberOption:
	//"{"
	//    "\"optionType\"" ":" "\"number\"" ","
	//    "\"min\"" ":" min=INT ","
	//    "\"max\"" ":" max=INT
	//    "\"range\"" ":" range=INT
	//"}"
	//;
	public NumberOptionElements getNumberOptionAccess() {
		return pNumberOption;
	}
	
	public ParserRule getNumberOptionRule() {
		return getNumberOptionAccess().getRule();
	}
	
	//FormInputSearch:
	//"{"
	//    "\"inputName\"" ":" name=STRING ","
	//    "\"inputType\"" ":" "\"search\"" ","
	//     "\"data\"" ":"  "[" data+=OptionItem ("," data+=OptionItem)* "]"
	//"}"
	//;
	public FormInputSearchElements getFormInputSearchAccess() {
		return pFormInputSearch;
	}
	
	public ParserRule getFormInputSearchRule() {
		return getFormInputSearchAccess().getRule();
	}
	
	//OptionItem:
	//    StringOptionItem | IntOptionItem | DataOptionItem
	//;
	public OptionItemElements getOptionItemAccess() {
		return pOptionItem;
	}
	
	public ParserRule getOptionItemRule() {
		return getOptionItemAccess().getRule();
	}
	
	//StringOptionItem:
	//    value=STRING
	//;
	public StringOptionItemElements getStringOptionItemAccess() {
		return pStringOptionItem;
	}
	
	public ParserRule getStringOptionItemRule() {
		return getStringOptionItemAccess().getRule();
	}
	
	//IntOptionItem:
	//    value=INT
	//;
	public IntOptionItemElements getIntOptionItemAccess() {
		return pIntOptionItem;
	}
	
	public ParserRule getIntOptionItemRule() {
		return getIntOptionItemAccess().getRule();
	}
	
	//DataOptionItem:
	//    value=Data
	//;
	public DataOptionItemElements getDataOptionItemAccess() {
		return pDataOptionItem;
	}
	
	public ParserRule getDataOptionItemRule() {
		return getDataOptionItemAccess().getRule();
	}
	
	//FormInputGroup:
	//    "name" ":" name=STRING ","
	//    "type:" "GROUP" ","
	//    "groupInputs:"  groupInputs=[FormInput]
	//;
	public FormInputGroupElements getFormInputGroupAccess() {
		return pFormInputGroup;
	}
	
	public ParserRule getFormInputGroupRule() {
		return getFormInputGroupAccess().getRule();
	}
	
	//Data:
	//    StringData | IntData;
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}
	
	//StringData:
	//    "{"
	//           "label:" label=STRING ","
	//        "value:" value=STRING
	//    "}";
	public StringDataElements getStringDataAccess() {
		return pStringData;
	}
	
	public ParserRule getStringDataRule() {
		return getStringDataAccess().getRule();
	}
	
	//IntData:
	//    "{"
	//           "label:" label=STRING ","
	//        "value:" value=INT
	//    "}";
	public IntDataElements getIntDataAccess() {
		return pIntData;
	}
	
	public ParserRule getIntDataRule() {
		return getIntDataAccess().getRule();
	}
	
	//terminal LAYOUT:
	//    "\"horizontal\""|"\"vertical\"" ;
	public TerminalRule getLAYOUTRule() {
		return tLAYOUT;
	}
	
	//terminal BASICINPUT:
	//    ("\"text\""|"\"checkbox\""|"\"numberr\""|"\"date\"")
	//;
	public TerminalRule getBASICINPUTRule() {
		return tBASICINPUT;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
