/**
 * generated by Xtext 2.28.0
 */
package cafev.vform.vFormDsl.impl;

import cafev.vform.vFormDsl.FormInput;
import cafev.vform.vFormDsl.VFormDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Form Input</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cafev.vform.vFormDsl.impl.FormInputImpl#getName <em>Name</em>}</li>
 *   <li>{@link cafev.vform.vFormDsl.impl.FormInputImpl#getId <em>Id</em>}</li>
 *   <li>{@link cafev.vform.vFormDsl.impl.FormInputImpl#getQC <em>QC</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FormInputImpl extends MinimalEObjectImpl.Container implements FormInput
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected static final String ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getId() <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getId()
   * @generated
   * @ordered
   */
  protected String id = ID_EDEFAULT;

  /**
   * The default value of the '{@link #getQC() <em>QC</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQC()
   * @generated
   * @ordered
   */
  protected static final String QC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getQC() <em>QC</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQC()
   * @generated
   * @ordered
   */
  protected String qC = QC_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FormInputImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VFormDslPackage.Literals.FORM_INPUT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VFormDslPackage.FORM_INPUT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getId()
  {
    return id;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setId(String newId)
  {
    String oldId = id;
    id = newId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VFormDslPackage.FORM_INPUT__ID, oldId, id));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getQC()
  {
    return qC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setQC(String newQC)
  {
    String oldQC = qC;
    qC = newQC;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VFormDslPackage.FORM_INPUT__QC, oldQC, qC));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VFormDslPackage.FORM_INPUT__NAME:
        return getName();
      case VFormDslPackage.FORM_INPUT__ID:
        return getId();
      case VFormDslPackage.FORM_INPUT__QC:
        return getQC();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VFormDslPackage.FORM_INPUT__NAME:
        setName((String)newValue);
        return;
      case VFormDslPackage.FORM_INPUT__ID:
        setId((String)newValue);
        return;
      case VFormDslPackage.FORM_INPUT__QC:
        setQC((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VFormDslPackage.FORM_INPUT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case VFormDslPackage.FORM_INPUT__ID:
        setId(ID_EDEFAULT);
        return;
      case VFormDslPackage.FORM_INPUT__QC:
        setQC(QC_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VFormDslPackage.FORM_INPUT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case VFormDslPackage.FORM_INPUT__ID:
        return ID_EDEFAULT == null ? id != null : !ID_EDEFAULT.equals(id);
      case VFormDslPackage.FORM_INPUT__QC:
        return QC_EDEFAULT == null ? qC != null : !QC_EDEFAULT.equals(qC);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", id: ");
    result.append(id);
    result.append(", qC: ");
    result.append(qC);
    result.append(')');
    return result.toString();
  }

} //FormInputImpl
