/**
 * generated by Xtext 2.28.0
 */
package cafev.vform.vFormDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Form Input Group</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cafev.vform.vFormDsl.FormInputGroup#getGroupInputs <em>Group Inputs</em>}</li>
 * </ul>
 *
 * @see cafev.vform.vFormDsl.VFormDslPackage#getFormInputGroup()
 * @model
 * @generated
 */
public interface FormInputGroup extends FormInput
{
  /**
   * Returns the value of the '<em><b>Group Inputs</b></em>' containment reference list.
   * The list contents are of type {@link cafev.vform.vFormDsl.FormInput}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group Inputs</em>' containment reference list.
   * @see cafev.vform.vFormDsl.VFormDslPackage#getFormInputGroup_GroupInputs()
   * @model containment="true"
   * @generated
   */
  EList<FormInput> getGroupInputs();

} // FormInputGroup
