/**
 * generated by Xtext 2.28.0
 */
package cafev.vform.vFormDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Option Item</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cafev.vform.vFormDsl.VFormDslPackage#getOptionItem()
 * @model
 * @generated
 */
public interface OptionItem extends EObject
{
} // OptionItem
