/*
 * generated by Xtext 2.25.0
 */
package cafeV.dsl.vforms.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVformDSLScopeProvider extends DelegatingScopeProvider {
}
