/*
 * generated by Xtext 2.30.0
 */
package yamtl.vforms.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class VFormsDslWebModule extends AbstractVFormsDslWebModule {
}
