/*
 * generated by Xtext 2.25.0
 */
package cafeV.dsl.vforms.serializer;

import cafeV.dsl.vforms.services.VformDSLGrammarAccess;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class VformDSLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected VformDSLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_EnumOption___OptionTypeKeyword_0_0_EnumKeyword_0_1_DataKeyword_0_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (VformDSLGrammarAccess) access;
		match_EnumOption___OptionTypeKeyword_0_0_EnumKeyword_0_1_DataKeyword_0_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEnumOptionAccess().getOptionTypeKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getEnumOptionAccess().getEnumKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getEnumOptionAccess().getDataKeyword_0_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_EnumOption___OptionTypeKeyword_0_0_EnumKeyword_0_1_DataKeyword_0_2__q.equals(syntax))
				emit_EnumOption___OptionTypeKeyword_0_0_EnumKeyword_0_1_DataKeyword_0_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('optionType' 'enum' 'data')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_EnumOption___OptionTypeKeyword_0_0_EnumKeyword_0_1_DataKeyword_0_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
