/**
 * generated by Xtext 2.28.0
 */
package cafev.vform.vFormDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Form Input Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cafev.vform.vFormDsl.FormInputSelect#getId <em>Id</em>}</li>
 *   <li>{@link cafev.vform.vFormDsl.FormInputSelect#getQC <em>QC</em>}</li>
 *   <li>{@link cafev.vform.vFormDsl.FormInputSelect#getOption <em>Option</em>}</li>
 * </ul>
 *
 * @see cafev.vform.vFormDsl.VFormDslPackage#getFormInputSelect()
 * @model
 * @generated
 */
public interface FormInputSelect extends FormInput
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see cafev.vform.vFormDsl.VFormDslPackage#getFormInputSelect_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link cafev.vform.vFormDsl.FormInputSelect#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>QC</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>QC</em>' attribute.
   * @see #setQC(String)
   * @see cafev.vform.vFormDsl.VFormDslPackage#getFormInputSelect_QC()
   * @model
   * @generated
   */
  String getQC();

  /**
   * Sets the value of the '{@link cafev.vform.vFormDsl.FormInputSelect#getQC <em>QC</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>QC</em>' attribute.
   * @see #getQC()
   * @generated
   */
  void setQC(String value);

  /**
   * Returns the value of the '<em><b>Option</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Option</em>' containment reference.
   * @see #setOption(Option)
   * @see cafev.vform.vFormDsl.VFormDslPackage#getFormInputSelect_Option()
   * @model containment="true"
   * @generated
   */
  Option getOption();

  /**
   * Sets the value of the '{@link cafev.vform.vFormDsl.FormInputSelect#getOption <em>Option</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Option</em>' containment reference.
   * @see #getOption()
   * @generated
   */
  void setOption(Option value);

} // FormInputSelect
