/**
 * generated by Xtext 2.28.0
 */
package cafev.vform.vFormDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Form Input Group</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cafev.vform.vFormDsl.FormInputGroup#getGroupInputs <em>Group Inputs</em>}</li>
 * </ul>
 *
 * @see cafev.vform.vFormDsl.VFormDslPackage#getFormInputGroup()
 * @model
 * @generated
 */
public interface FormInputGroup extends FormInput
{
  /**
   * Returns the value of the '<em><b>Group Inputs</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group Inputs</em>' reference.
   * @see #setGroupInputs(FormInput)
   * @see cafev.vform.vFormDsl.VFormDslPackage#getFormInputGroup_GroupInputs()
   * @model
   * @generated
   */
  FormInput getGroupInputs();

  /**
   * Sets the value of the '{@link cafev.vform.vFormDsl.FormInputGroup#getGroupInputs <em>Group Inputs</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group Inputs</em>' reference.
   * @see #getGroupInputs()
   * @generated
   */
  void setGroupInputs(FormInput value);

} // FormInputGroup
