/*
 * generated by Xtext 2.28.0
 */
package cafev.vform.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class VFormDslWebModule extends AbstractVFormDslWebModule {
}
