/*
 * generated by Xtext 2.28.0
 */
package cafev.vform.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VFormDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("cafev/vform/parser/antlr/internal/InternalVFormDsl.tokens");
	}
}
