/**
 * generated by Xtext 2.28.0
 */
package cafev.vform.tests;

import cafev.vform.vFormDsl.Model;

/* @ExtendWith(/* name is null */)
@InjectWith(VFormDslInjectorProvider.class) */@SuppressWarnings("all")
public class VFormDslParsingTest {
  /* @Inject
   */private /* ParseHelper<Model> */Object parseHelper;

  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nThe field VFormDslParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
