/*
 * generated by Xtext 2.25.0
 */
package cafeV.dsl.vforms.parser.antlr;

import cafeV.dsl.vforms.parser.antlr.internal.InternalVformDSLParser;
import cafeV.dsl.vforms.services.VformDSLGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class VformDSLParser extends AbstractAntlrParser {

	@Inject
	private VformDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVformDSLParser createParser(XtextTokenStream stream) {
		return new InternalVformDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public VformDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VformDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
