/*
 * generated by Xtext 2.30.0
 */
package yamtl.vforms.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import yamtl.vforms.VFormsDslRuntimeModule;
import yamtl.vforms.VFormsDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class VFormsDslIdeSetup extends VFormsDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new VFormsDslRuntimeModule(), new VFormsDslIdeModule()));
	}
	
}
